import { component$ } from "@builder.io/qwik";

export const RouterHeadFonts = component$(() => {
  return (
    <>
      <link
        rel="preload"
        href="/fonts/Poppins-Bold.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />

      <link
        rel="preload"
        href="/fonts/Poppins-Italic.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-Regular.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-Medium.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-MediumItalic.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-SemiBold.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-SemiBoldItalic.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-Bold.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Poppins-BoldItalic.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
    </>
  );
});
